### PR TITLE
feature/v2

### PR DESCRIPTION
**Pull request by busticated**
just some house cleaning - mainly to address [GH's security alerts](https://github.com/particle-iot/wiring-preprocessor/network/alerts). proposing `v2` since going forward we won't be supporting node `v4` and `v6`.

edit: but for the public / open-source bit, this lib would also be a good fit for our `js-utils` collection

### CODE REVIEW

**Comment by busticated** [comment]
@monkbroc 

> Since you're in here, do you want to add the header // THIS IS AN AUTOGENERATED FILE, DO NOT MODIFY that you had proposed a while back?

ah, yeah. good call :+1:

what's the situation on publishing privileges? do you need to add me as a collaborator?

**Comment by monkbroc** [comment]
> do you need to add me as a collaborator?

Done.

**Comment by busticated** [comment]
@monkbroc updated. how much does it matter that we are exclusively using unix-style newlines in the generated `.cpp` files? i assume not at all since i haven't seen any errors due to this over in Workbench but 🤷‍♂

**Comment by monkbroc** [comment]
Until we hear otherwise we can keep unix newlines.

**Pull request merged**
